model:
  backbone: timm_resnet50 # Must match stage-one training
  num_classes: 3

dataloaders:
  train_batch_size: 4
  valid_batch_size: 4
  num_workers: 0

optimizer:
  name: SGD # Optimizer type
  params:
    lr: 0.001 # Learning rate

criterion:
  name: 'CrossEntropy' # Loss function for multi-class classification
